name: Run tests

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: "Installs dependencies"
        run: |
          pip install -U pip wheel
          pip install -r requirements-test.txt

      - name: "Test"
        run: make test
