name: run_tests
on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: tests
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: "Installs dependencies"
        run: |
          pip install -U uv
          uv pip install -r requirements-test.txt

      - name: "Test"
        run: make test
