name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Installs dependencies"
        run: |
          pip install -U uv
          uv sync --group dev --group test
          pip install -e .
      - run: make lint
  tests:
    name: tests
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: "Installs dependencies"
        run: |
          pip install -U uv
          uv sync --group dev --group test
          pip install -e .
      - run: make test
